/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoomImport } from './routes/room'
import { Route as IndexImport } from './routes/index'
import { Route as TestAbcImport } from './routes/test/abc'

// Create/Update Routes

const RoomRoute = RoomImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestAbcRoute = TestAbcImport.update({
  id: '/test/abc',
  path: '/test/abc',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomImport
      parentRoute: typeof rootRoute
    }
    '/test/abc': {
      id: '/test/abc'
      path: '/test/abc'
      fullPath: '/test/abc'
      preLoaderRoute: typeof TestAbcImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room': typeof RoomRoute
  '/test/abc': typeof TestAbcRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room': typeof RoomRoute
  '/test/abc': typeof TestAbcRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/room': typeof RoomRoute
  '/test/abc': typeof TestAbcRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room' | '/test/abc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room' | '/test/abc'
  id: '__root__' | '/' | '/room' | '/test/abc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoute: typeof RoomRoute
  TestAbcRoute: typeof TestAbcRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoute: RoomRoute,
  TestAbcRoute: TestAbcRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/room",
        "/test/abc"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/room": {
      "filePath": "room.tsx"
    },
    "/test/abc": {
      "filePath": "test/abc.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
